/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void test1() {
        assertTrue(1 + 1 == 2);
    }

    @Test
    void test2() {
        assertTrue(2 + 2 == 4);
    }

    @Test
    void test3() {
        assertTrue(3 + 3 == 6);
    }
}
